### PR TITLE
Add Geocoder.GeocodeAsync() to support async execution

### PR DESCRIPTION
**Pull request by andyzukunft**
GeocodeAsync() is implemented like ReverseGeocodeAsync() by calling GetResponseAsync() instead of GetResponse();

### CODE REVIEW

**Comment by freyfogle** [comment]
Hi, I'm Ed, one of the co-founders of OpenCage. Great work @andyzukunft on all these PRs. I hope they can be merged quickly

**Comment by andyzukunft** [comment]
Hey Ed,

happy to be of assistance. It's good to hear that you are open to PRs :+1:.

**Comment by freyfogle** [comment]
Hi, the issue is this repo is owned by @gingemonster not by OpenCage. While we do have official repos supported and developed by us (though of course also welcoming of outside contributions), dotnet is not a language we are familiar with. We rely on the open source community to help us there. 

Thanks again

**Comment by gingemonster** [comment]
Will take a look asap, also happy for someone to take this over if you are interested @andyzukunft

**Comment by andyzukunft** [comment]
@gingemonster 
If you don't have the time anymore I can bear the torch.

**Pull request merged**
