### PR TITLE
Feature add roadinfo

### PR DESCRIPTION
**Pull request by andyzukunft**
Implement parameter roadinfo in the same way as other additional parameters are implemented.

This implementation is based on #17.

### CODE REVIEW

**Comment by andyzukunft** [comment]
Btw I forgot to mention this: the flag is being set and sent. However I didn't see any change in behaviour - independently of setting `roadinfo=1`, `roadinfo=0` or not sending roadinfo at all.

Maybe you can provide me with Coordinates or a Query and I can verify that it does change it's behaviour.

**Comment by freyfogle** [comment]
Sure, try the OpenCage office at `52.3877830, 9.7334394`

Without `roadinfo=1` 

```
"components": {
        "ISO_3166-1_alpha-2": "DE",
        "ISO_3166-1_alpha-3": "DEU",
        "ISO_3166-2": [
          "DE-NI"
        ],
        "_category": "building",
        "_type": "building",
        "city": "Hanover",
        "city_district": "Vahrenwald-List",
        "continent": "Europe",
        "country": "Germany",
        "country_code": "de",
        "county": "Region Hannover",
        "house_number": "2",
        "office": "Design Offices",
        "political_union": "European Union",
        "postcode": "30165",
        "road": "Philipsbornstraße",
        "state": "Lower Saxony",
        "state_code": "NI",
        "suburb": "Vahrenwald"
      },
      "confidence": 10,
      "formatted": "Design Offices, Philipsbornstraße 2, 30165 Hanover, Germany",
```

with `roadinfo=1`

```
      "components": {
        "ISO_3166-1_alpha-2": "DE",
        "ISO_3166-1_alpha-3": "DEU",
        "ISO_3166-2": [
          "DE-NI"
        ],
        "_category": "road",
        "_type": "road",
        "city": "Hanover",
        "city_district": "Vahrenwald-List",
        "continent": "Europe",
        "country": "Germany",
        "country_code": "de",
        "county": "Region Hannover",
        "political_union": "European Union",
        "postcode": "30165",
        "road": "Philipsbornstraße",
        "road_type": "tertiary",
        "state": "Lower Saxony",
        "state_code": "NI",
        "suburb": "Vahrenwald"
      },
      "confidence": 9,
      "formatted": "Philipsbornstraße, 30165 Hanover, Germany",
```

notice the `_type` value changes from building to road. There is also different info in the `roadinfo` annotation portion of the result.

Easiest place to quickly test for yourself is the [OpenCage geocoding demo page](https://opencagedata.com/demo)

Please let me know if I misunderstood your question.

Thanks again

**Comment by andyzukunft** [comment]
Thanks for the example data Ed.

I executed my test against `52.3877830, 9.7334394`.

Generated Urls:
```
https://api.opencagedata.com/geocode/v1/json?q=52.387783%2C9.7334394&key=MyKey&language=de&limit=10&abbrv=1
https://api.opencagedata.com/geocode/v1/json?q=52.387783%2C9.7334394&key=MyKey&language=de&limit=10&abbrv=1&roadInfo=0
https://api.opencagedata.com/geocode/v1/json?q=52.387783%2C9.7334394&key=MyKey&language=de&limit=10&abbrv=1&roadInfo=1
```

All three results are identical. I am attaching the results as json files to keep this comment concise:
[OpenCage_Coords_Geocode_Results.zip](https://github.com/gingemonster/dotnet-opencage-geocode/files/12774684/OpenCage_Coords_Geocode_Results.zip)

If you can confirm the api Url is correct I would suggest this might be a problem on your backend.

Btw: stop working on weekend guys. This has no rush.

**Comment by freyfogle** [comment]
well this one didn't take a lot of sleuthing, the parameter should be `roadinfo` not `RoadInfo`

https://opencagedata.com/api#roadinfo-param

I guess we can add a step to lowercase all incoming params

**Comment by andyzukunft** [comment]
Ahhh! Copy&Paste error. Thanks, I will fix it.

But yeah, handling the incoming parameter case insensitive sure would be a good idea.

**Pull request merged**
